<?php

namespace App\Repositories\FmaRepBusiness;

class StoredFunctions
{
    CONST PS_GET_ALL_CANDIDATE ="PS_GET_ALL_CANDIDATE";
    CONST PS_INSERTUPDATE_CANDIDATE = 'PS_INSERTUPDATE_CANDIDATE';
    CONST PS_INSERTUPDATE_SKILL = 'PS_INSERTUPDATE_SKILL';
    CONST PS_INSERTUPDATE_EDUCATION = 'PS_INSERTUPDATE_EDUCATION';
    CONST PS_INSERTUPDATE_EXPERIENCE = 'PS_INSERTUPDATE_EXPERIENCE';
    CONST PS_INSERTUPDATE_INSERTUPDATE_TMPTEMP = 'PS_INSERTUPDATE_TMPTEMP';
    CONST PS_GET_TEMPTEMPLATE ='PS_GET_TEMPTEMPLATE';
}
